ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS coupon_code TEXT,
ADD COLUMN IF NOT EXISTS discount DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS wallet_amount DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_delivery_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS estimated_delivery_date DATE;
