// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Bypass navigator.locks contention that can stall auth calls on some browsers/devices.
const noOpLock = async <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
  return fn();
};

const createSupabaseClient = () => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Missing Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be defined');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      lock: noOpLock,
    },
  });
};

type SupabaseClientCache = {
  _supabaseClient?: ReturnType<typeof createSupabaseClient>;
};

const globalScope = globalThis as unknown as SupabaseClientCache;

// Cache the client instance in development to avoid multiple instances during HMR
export const supabase = import.meta.env.DEV
  ? (globalScope._supabaseClient ??= createSupabaseClient())
  : createSupabaseClient();
